### ISSUE TITLE
has_collection is not working

### ISSUE THREAD

**Issue by rrajaravi** [sourcepirate/lagoon#1]
- has_collection is not working as expected

**Comment by sourcepirate** [comment]
what is happening any error msg ?

**Comment by sourcepirate** [comment]
Closing this issue because this is fixed in commit https://github.com/sourcepirate/lagoon/commit/d8168700e87735a1e487814a12aee223101c45b7

**Comment by sourcepirate** [comment]
Feel free to open if its not behaving expected.
